name: Linting, testing, building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install modules
        run: npm install
      - name: build storybook
        run: npm run build-storybook
      - name: screenshot testing unresolved bug with new loki version with storybook 7+.
        run: npm run test:ui:ci
